name: Setup test environment
description: Shared setup for vhs_decode tests

inputs:
  python-version:
    required: true
    description: Python version to use

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version:  ${{ inputs.python-version }}

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libportaudio2

    - uses: dtolnay/rust-toolchain@stable

    - name: Install package with test dependencies
      shell: bash
      run: pip install ".[test]"

